project:
  type: website

website:
  title: "warmup-sean-switzer"
  site-path: "/warmup-sean-switzer/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: articles/index.qmd
        text: Articles
      - href: article_01.qmd
        text: test

  sidebar:
    - id: articles
      title: "Articles"
      style: "docked"
      background: dark
      collapse-level: 2
      contents: 
        - text: "Article One"
          href:  articles/article_01.qmd
        - text: "Article Two"
          href:  articles/article_02.qmd

format:
  html:
    theme: vapor
    css: styles.css
    toc: true



