project:
  type: website
  output-dir: docs

website:
  title: "Sean's Webpage"
  site-path: "/personal-sean-switzer/"
  favicon: /images/favicon.png
  navbar:
    logo: /images/wolf.png
    background: transparent
    foreground: "#FFFFFF"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: articles/index.qmd
        text: Articles
      - href: posts/index.qmd
        text: Blog


  sidebar:
    - id: none
      style: "docked"
      background: transparent
      foreground: "#FFFFFF"
      collapse-level: 2
      contents: 
      - section: "Articles"
        href: articles/index.qmd
        contents: 
          - text: "A Class Called Group"
            href:  articles/article_01.qmd
          - text: "Recursive Recursion"
            href:  articles/article_02.qmd
          - text: "Recustomizing a Site"
            href:  articles/article_03.qmd
      - section: "Posts"
        href: posts/index.qmd
        contents: "posts/*/*.qmd"
        sort:
          - "date desc"

format:
  html:
    theme: styles.css
    fontcolor: "#FFFFFF"
    linkcolor: "#ccff99"
    css: styles.css
    toc: true




